#ifdef GET_BinRequirementKindEnum_DECL
enum BinRequirementKindEnum {
  BRK_0_to_4 = 0,
  BRK_0_to_4_dbl = 1,
  BRK_0_to_4_hi = 2,
  BRK_0_to_4_lo = 3,
  BRK_0_to_6 = 4,
  BRK_0_to_6_dbl = 5,
  BRK_0_to_6_hi = 6,
  BRK_0_to_6_lo = 7,
  BRK_2_to_4 = 8,
  BRK_2_to_4_dbl = 9,
  BRK_2_to_4_hi = 10,
  BRK_2_to_4_lo = 11,
  BRK_2_to_6 = 12,
  BRK_2_to_6_dbl = 13,
  BRK_2_to_6_hi = 14,
  BRK_2_to_6_lo = 15,
};
#endif

#ifdef GET_SymKind_DECL
enum SymKind {
  SK_a = 0,
  SK_b = 1,
  SK_c = 2,
  SK_d = 3,
};
#endif

#undef GET_BinRequirementKindEnum_DECL
#undef GET_SymKind_DECL
