# Autogenerated from C:/Users/mateb/OneDrive/Desktop/Projekti/LLVM/llvm-project_17_0_1/llvm/test/Unit/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
from pathlib import Path
def path(p):
    if not p: return ''
    return str((Path(__file__).parent / p).resolve())


import sys

config.llvm_src_root = path(r"..\..\..\llvm-project_17_0_1\llvm")
config.llvm_obj_root = path(r"..\..")
config.llvm_tools_dir = lit_config.substitute(path(r"..\..\%(build_mode)s\bin"))
config.llvm_build_mode = lit_config.substitute("%(build_mode)s")
config.shlibdir = lit_config.substitute(path(r"..\..\%(build_mode)s\bin"))

# Let the main config do the real work.
lit_config.load_config(
    config, os.path.join(config.llvm_src_root, "test/Unit/lit.cfg.py"))
